engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.rake"
  - "**.slim"
  - "**.scss"
  - "**.js"
exclude_paths:
- app/assets/images/*
- bin/*
- config/**/*
- db/**/*
- log/*
- public/*
- vendor/**/*
- app/assets/javascripts/sorttable.js
- .rubocop.yml
- config.ru
- Gemfile
- Guardfile
- LICENSE
- Rakefile
