engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true

ratings:
  paths:
  - "**.js"
  - "**.rb"
  - "**.rake"
  - "**.slim"
  - "**.scss"
  - Gemfile.lock

exclude_paths:
- bin/*
- config/**/*
- db/**/*
- public/*
- vendor/**/*
- app/assets/javascripts/sorttable.js
- .rubocop.yml
