engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true

ratings:
  paths:
  - app/**/*
  - lib/**/*
  - Gemfile.lock

exclude_paths:
- app/assets/images*
- bin/*
- config/**/*
- db/**/*
- log/*
- public/**/*
- vendor/**/*
- .rubocop.yml
