require: rubocop-rails

AllCops:
  Include:
    - '**/*.rb'
    - '**/*.rake'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  TargetRubyVersion: 2.6

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
