inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - 'db/**/*'

Style/ClassMethodsDefinitions:
  EnforcedStyle: def_self
